### ISSUE TITLE
Add GitHub actions to automatically build new Docker images on update

### ISSUE THREAD

**Issue by FDelporte** [Pi4J/pi4j-docker#1]

**Comment by savageautomate** [comment]
This task has been completed with the inclusion of the "**Continuous Integration**" GitHub Action/Workflow.
 - https://github.com/Pi4J/pi4j-docker/actions/workflows/ci.yml
 - https://github.com/Pi4J/pi4j-docker/blob/master/.github/workflows/ci.yml

This workflow will build the following Docker images in the required order:
 - pi4j-builder-base
 - pi4j-builder-native
 - pi4j-builder-1.4
 - pi4j-builder-2.0

If each build succeeds, then it will also get automatically pushed/deployed to DockerHub
 - https://hub.docker.com/repositories/pi4j

![image](https://user-images.githubusercontent.com/2251458/110678092-e9f91680-81a3-11eb-9c7b-a52808022103.png)

---
**Note:** the necessary `secrets` (_DockerHub access credentials_) are stored at the Pi4J Organizational unit in GitHub.
